print("Question 1")
print(" ________________")
print("|               |")
print("|               |")
print("|               |")
print("|               |")
print("|               |")
print(" ________________")
