product=1

print("enter number to calculate product and average press q to exit")
#while loop will be terminated while pressing q
while user_quit!="q":
    num=int(input())
    user_list.oppend("num")
    user_quit=(input("wanna exit?"))

#loop to calculate average and product
for i in range(0,len(user_list)):
    sum+=user_list[1]
    print("average of user input number is:"), sum/len(user_list)
    print("product of number is:", product)
