print("_____________________ ")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|                   |")
print("|___________________|")