# write a program to print a square
print("--------------------------")
print("|                        |")
print("|                        |")
print("|                        |")
print("|                        |")
print("|                        |")
print("|                        |")
print("|                        |")
print("--------------------------")
