print("Question 1")
print(" _______________")
print("|               |")
print("|               |")
print("|               |")
print("|               |")
print("|               |")
print(" _______________")